services:
  flask_app:
    image: kgozdz/pawcho:main

    ports:
      - "5000:5000"
    volumes:
      - ./app/templates:/app/templates:ro
      - ./app/translations:/app/translations:ro

    networks:
      - app-network
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s = socket.socket(); s.connect(('localhost', 5000))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    

  nginx:
    image: nginx@sha256:9d6b58feebd2dbd3c56ab5853333d627cc6e281011cfd6050fa4bcf2072c9496
    ports:
      - "80:30160"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

      - ./app/static:/app/static:ro
      - ./app/templates:/app/templates:ro
      - ./app/translations:/app/translations:ro

    depends_on:
      flask_app:
        condition:  service_healthy
    networks:
      - app-network
    restart: always
  
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    command: --interval 30 --cleanup  kgozdz/pawcho 
    restart: always

networks:
  app-network:
    driver: bridge
